### ISSUE TITLE
Dialog hanging with no Internet connection 

### ISSUE THREAD

**Issue by missxa** [Roboy/DialogSystem#78]
When having `roboy.dialog.states.ordinaryStates.QuestionAnsweringState` in the personality file (even is no transitions to it are defined) the conversation won't start if there's no internet connection, since apparently the state is trying to resolve some http host forever.

**Comment by Aevyz** [comment]
Can't seem to replicate it unfortunately...

I pulled the Ethernet cable out right before entering input (can't earlier b/c #72 ) and it all seemed to work as expected, throwing `UnknownHostException` because of the lack of Internet, however it was not blocking/infinite looping and just continued on.


https://gist.github.com/Aevyz/60ad147472d3f13c27a989a762a64e0a
